package com.example.assignment2_cashregisterapp;

import androidx.activity.result.ActivityResultLauncher;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;

import android.widget.Button;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;
import android.content.Intent;

import java.util.Calendar;
import java.util.Date;
//Code Written By: Seema Shabadi 23/11/2022
public class MainActivity extends AppCompatActivity implements View.OnClickListener {
TextView product_type_text;
TextView product_qty_text;
TextView total_bill_text;
Button one_button;
Button two_button;
Button three_button;
Button four_button;
Button five_button;
Button six_button;
Button seven_button;
Button eight_button;
Button nine_button;
Button zero_button;
Button clear_Button;
Button buy_button;
Button manager_button;
ListView product_details_list;
//ActivityResultLauncher<Intent> managerActivityLauncher;
ProductDetailsList_CustomAdapter adapter;
double productPrice;
int selectedProductIndex;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        product_details_list = findViewById(R.id.product_list);
        product_type_text = findViewById(R.id.product_type);
        product_qty_text = findViewById(R.id.product_quantity);
        total_bill_text = findViewById(R.id.total_bill);
        one_button = findViewById(R.id.one_btn);
        two_button = findViewById(R.id.two_btn);
         three_button = findViewById(R.id.three_btn);
         four_button = findViewById(R.id.four_btn);
         five_button = findViewById(R.id.five_btn);
         six_button = findViewById(R.id.six_btn);
         seven_button = findViewById(R.id.seven_btn);
         eight_button = findViewById(R.id.eight_btn);
         nine_button = findViewById(R.id.nine_btn);
         zero_button = findViewById(R.id.zero_btn);
         clear_Button = findViewById(R.id.clear_btn);
         buy_button = findViewById(R.id.buy_btn);
         manager_button = findViewById(R.id.manager_btn);
         zero_button.setOnClickListener(this);
         one_button.setOnClickListener(this);
         two_button.setOnClickListener(this);
         three_button.setOnClickListener(this);
         four_button.setOnClickListener(this);
         five_button.setOnClickListener(this);
         six_button.setOnClickListener(this);
         seven_button.setOnClickListener(this);
         eight_button.setOnClickListener(this);
         nine_button.setOnClickListener(this);
         clear_Button.setOnClickListener(this);
         buy_button.setOnClickListener(this);
         manager_button.setOnClickListener(this);
         setTitle("Cash Register");
//We are using base adapter to display the list of product details in our first activity
        adapter = new ProductDetailsList_CustomAdapter(((MyApp)getApplication()).myStore.getList(),this);

        product_details_list.setAdapter(adapter);
        //Base adapter has all the implemented method ready for us whenever user clicks the row
product_details_list.setOnItemClickListener(new AdapterView.OnItemClickListener() {
    @Override
    public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
        product_type_text.setText(((MyApp)getApplication()).myStore.productDetails[i].prod_name);

        productPrice = ((MyApp)getApplication()).myStore.productDetails[i].prod_price;
        selectedProductIndex = i;
        if(!product_qty_text.getText().toString().equals("Quantity"))
            product_qty_text.setText("Quantity");
        if(!total_bill_text.getText().toString().equals("Total"))
            total_bill_text.setText("Total");
    }
});
    }
//Handle all the events that are generated by clicking on the buttons on first screen/activity
    @Override
    public void onClick(View view) {
        switch(view.getId())
        {
            case R.id.manager_btn:
                Intent toManagerIntent = new Intent(MainActivity.this,ManagerActivity.class);
                startActivity(toManagerIntent);
                break;
            case R.id.clear_btn:
                product_type_text.setText("Product Type");
                product_qty_text.setText("Quantity");
                total_bill_text.setText("Total");
                break;
            case R.id.buy_btn:
               if(product_type_text.getText().toString().equals("Product Type")||product_qty_text.getText().toString().equals("Quantity"))
                     {
                        Toast.makeText(MainActivity.this, "Please enter all fields information...", Toast.LENGTH_LONG).show();

                    }
                        else if(Integer.parseInt(product_qty_text.getText().toString())>((MyApp)getApplication()).myStore.productDetails[selectedProductIndex].prod_qty)
                    Toast.makeText(MainActivity.this,"Not enough quantity in the stock... ",Toast.LENGTH_LONG).show();
                else {
                    total_bill_text.setText(String.valueOf(String.format("%.2f",(Integer.parseInt(product_qty_text.getText().toString()) * productPrice))));
                    ((MyApp)getApplication()).myStore.productDetails[selectedProductIndex].updateQuantity(Integer.parseInt(product_qty_text.getText().toString()));
                    AlertDialog.Builder builder = new AlertDialog.Builder(this);
                    builder.setMessage("Thank you for your purchase! " + "You purchased " + product_qty_text.getText().toString() + " " + product_type_text.getText().toString() +" for $"+ total_bill_text.getText().toString()).create().show();
                   Date purchaseDateTime = Calendar.getInstance().getTime();
                    PurchaseHistory newPurchaseHistory = new PurchaseHistory(product_type_text.getText().toString(),Integer.parseInt(product_qty_text.getText().toString()),Double.parseDouble(total_bill_text.getText().toString()),purchaseDateTime.toString());
                    ((MyApp)getApplication()).myStore.addNewPurchaseHistory(newPurchaseHistory);
                }

                adapter.prod_list = ((MyApp)getApplication()).myStore.getList();
                adapter.notifyDataSetChanged();
                break;
            default:
                if(product_qty_text.getText().toString().equals("Quantity"))
                product_qty_text.setText(((Button)view).getText().toString());
                else
                    product_qty_text.setText(product_qty_text.getText().toString()+((Button)view).getText().toString());
        }

    }
}